Added LDAP_MEMBER_ATTRIBUTE, changed LDAP_CONFIG_BASE_DN

diff --git a/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew b/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew
--- a/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew
+++ b/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew
@@ -47,6 +47,12 @@ else
     echo -e "LDAP_USERNAME_ATTRIBUTE cannot be set, check UCR variable 'guacamole/ldap/username/attribute'!"
     exit 1
 fi
+if [ "${guacamole_ldap_member_attribute}" ]; then
+    echo -e "LDAP_MEMBER_ATTRIBUTE can be set"
+else
+    echo -e "LDAP_MEMBER_ATTRIBUTE cannot be set, check UCR variable 'guacamole/ldap/member/attribute'!"
+    exit 1
+fi
 if [ "${guacamole_external_port}" ]; then
     echo -e "External port can be set"
 else
@@ -114,6 +120,7 @@ echo -n "Creating new Guacamole container... "
     -e LDAP_USER_BASE_DN="${guacamole_user_dn}" \
     -e LDAP_CONFIG_BASE_DN="${guacamole_config_base_dn}" \
     -e LDAP_USERNAME_ATTRIBUTE="${guacamole_ldap_username_attribute}" \
+    -e LDAP_MEMBER_ATTRIBUTE="${guacamole_ldap_member_attribute}" \
     -e LDAP_SEARCH_BIND_DN="uid=guacamole-${hostname},cn=users,${ldap_base}" \
     -e LDAP_SEARCH_BIND_PASSWORD="$(cat /etc/guacamole.secret)" \
     -e LDAP_USER_SEARCH_FILTER="${guacamole_ldap_user_searchfilter}" \
