univention-guacamole: Actualised for UCS 4.3 and UCS App Center #8197

diff --git a/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew b/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew
--- a/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew
+++ b/univention-guacamole-ldap-connection/usr/bin/univention-guacamole-renew
@@ -1,6 +1,4 @@
 #!/bin/bash
-# installation joinscript for univention-guacamole-rollout
-#
 # Copyright (C) 2017-2018 Univention GmbH
 #
 # http://www.univention.de/
@@ -27,11 +25,6 @@
 # License with the Debian GNU/Linux or Univention distribution in file
 # /usr/share/common-licenses/AGPL-3; if not, see
 # <http://www.gnu.org/licenses/>.
-
-VERSION=3
-
-. /usr/share/univention-join/joinscripthelper.lib
-joinscript_init
 
 eval "$(ucr shell)"
 
@@ -61,10 +54,10 @@ else
     exit 1
 fi
 if [ "${guacamole_ldap_user_searchfilter}" ]; then
-	echo -e "LDAP_USER_SEARCH_FILTER can be set"
+    echo -e "LDAP_USER_SEARCH_FILTER can be set"
 else
-	echo -e "LDAP_USER_SEARCH_FILTER cannot be set, check UCR variables 'guacamole/ldap/user/searchfilter'!"
-	exit 1
+    echo -e "LDAP_USER_SEARCH_FILTER cannot be set, check UCR variables 'guacamole/ldap/user/searchfilter'!"
+    exit 1
 fi
 if [ -e /etc/guacamole.secret ]; then
     echo "Search user can be used"
@@ -73,32 +66,45 @@ else
     exit 1
 fi
 
-if joinscript_check_any_version_executed; then
-	echo -n "Removing old Guacd container... "
-	/usr/bin/docker stop guacd > /dev/null
-	/usr/bin/docker rm guacd > /dev/null
-	echo -e "Done!"
+echo -e ""
+echo -e "Creating new container for Guacamole"
+echo -e "---------------"
+
+if [ $(/usr/bin/docker ps -q -f name=guacd) ]; then
+    echo -n "Stopping and removing old Guacd container... "
+    /usr/bin/docker stop guacd > /dev/null
+    /usr/bin/docker rm guacd > /dev/null
+    echo -e "Done!"
 fi
 
-echo -e "Downloading and installing guacd... "
+echo -n "Creating new Guacd container... "
 /usr/bin/docker run \
     --name guacd \
     --restart=always \
-    -d guacamole/guacd:0.9.13-incubating
+    -d guacamole/guacd:0.9.13-incubating > /dev/null
 echo -e "Done!"
 
 
-if joinscript_check_any_version_executed; then
-	echo -n "Removing old Guacamole container to provision new container with new settings... "
-	/usr/bin/docker stop guacamole > /dev/null
-	/usr/bin/docker rm guacamole > /dev/null
-	echo -e "Done!"
+if [ $(/usr/bin/docker ps -q -f name=guacamole) ]; then
+    if [ "0.0.0.0:${guacamole_external_port}" != "$(/usr/bin/docker port guacamole 8080)" ]; then
+        echo -n "External port changed. Reloading apache2 server... "
+        systemctl reload apache2.service
+
+        # apache2 failed to reload successfully. Warn the User
+        if [ $? != 0 ]; then
+            echo "ERROR: apache2 failed to reload. Check your log files for further help."
+            exit 1
+        fi
+        echo -e "Done!"
+    fi
+
+    echo -n "Stopping and removing old Guacamole container... "
+    /usr/bin/docker stop guacamole > /dev/null
+    /usr/bin/docker rm guacamole > /dev/null
+    echo -e "Done!"
 fi
 
-# Sleep five seconds to let Docker rest before creating the new container
-sleep 5s
-
-echo -e "Downloading and installing Guacamole... "
+echo -n "Creating new Guacamole container... "
 /usr/bin/docker run \
     --name guacamole \
     --link guacd:guacd \
@@ -108,38 +114,13 @@ echo -e "Downloading and installing Guacamole... "
     -e LDAP_USER_BASE_DN="${guacamole_user_dn}" \
     -e LDAP_CONFIG_BASE_DN="${guacamole_config_base_dn}" \
     -e LDAP_USERNAME_ATTRIBUTE="${guacamole_ldap_username_attribute}" \
-    -e LDAP_SEARCH_BIND_DN="uid=guacamole,cn=users,${ldap_base}" \
+    -e LDAP_SEARCH_BIND_DN="uid=guacamole-${hostname},cn=users,${ldap_base}" \
     -e LDAP_SEARCH_BIND_PASSWORD="$(cat /etc/guacamole.secret)" \
-	-e LDAP_USER_SEARCH_FILTER="${guacamole_ldap_user_searchfilter}" \
-    -d -p "${guacamole_external_port}":8080 guacamole/guacamole:0.9.13-incubating
-echo -e "Done!"
-
-echo -n "Installing patched LDAP auth plugin... "
+    -e LDAP_USER_SEARCH_FILTER="${guacamole_ldap_user_searchfilter}" \
+    -d -p "${guacamole_external_port}":8080 guacamole/guacamole:0.9.13-incubating > /dev/null
 /usr/bin/docker cp /usr/share/guacamole/guacamole-auth-ldap-* guacamole:/opt/guacamole/ldap/
-echo -e "Done!"
-
-echo -n "Installing patched start script to use LDAP_USER_SEARCH_FILTER..."
 /usr/bin/docker cp /usr/share/guacamole/start.sh guacamole:/opt/guacamole/bin
+/usr/bin/docker restart guacamole > /dev/null
 echo -e "Done!"
 
-echo -e "Restarting Container Guacamole for using patched plugin..."
-/usr/bin/docker restart guacamole
-echo -e "Done!"
-
-echo -e "Configure Apache2 site for Guacamole... "
-/usr/sbin/univention-config-registry commit /etc/apache2/sites-available/guacamole.conf
-a2ensite guacamole.conf
-service apache2 reload
-echo -e "Done!"
-
-echo -e "Create overview site link... "
-/usr/sbin/univention-config-registry set \
-    ucs/web/overview/entries/service/guacamole/link="/guacamole" \
-    ucs/web/overview/entries/service/guacamole/label="Guacamole" \
-    ucs/web/overview/entries/service/guacamole/description="Guacamole is a clientless remote desktop gateway." \
-    ucs/web/overview/entries/service/guacamole/description/de="Guacamole ist ein clientloses Gateway für Remote-Verbindungen." \
-    ucs/web/overview/entries/service/guacamole/icon="/guacamole/images/logo-64.png"
-echo -e "Done!"
-
-joinscript_save_current_version
 exit 0
