convert tabs to spaces

diff --git a/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert b/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert
--- a/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert
+++ b/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert
@@ -30,13 +30,13 @@
 DIR_LE="/etc/univention/letsencrypt"
 
 if [ ! "$(id -un)" = "letsencrypt" ] ; then
-	echo "ERROR: please restart this script as user 'letsencrypt'."
-	exit 1
+    echo "ERROR: please restart this script as user 'letsencrypt'."
+    exit 1
 fi
 
 cleanup () {
-	set +e
-	[ -n "$TMPFN" -a -f "$TMPFN" ] && rm -f "$TMPFN"
+    set +e
+    [ -n "$TMPFN" -a -f "$TMPFN" ] && rm -f "$TMPFN"
 }
 trap cleanup EXIT
 TMPFN="$(mktemp --tmpdir="$DIR_LE")"
diff --git a/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert-cron b/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert-cron
--- a/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert-cron
+++ b/univention-letsencrypt/usr/share/univention-letsencrypt/refresh-cert-cron
@@ -33,8 +33,8 @@ eval "$(ucr shell)"
 DIR_LE="/etc/univention/letsencrypt"
 
 if [ ! "$(id -un)" = "root" ] ; then
-	echo "ERROR: please restart this script as user 'root'."
-	exit 1
+    echo "ERROR: please restart this script as user 'root'."
+    exit 1
 fi
 
 su - letsencrypt -c "/usr/share/univention-letsencrypt/refresh-cert"
@@ -43,31 +43,31 @@ openssl x509 -in "$DIR_LE/signed.crt" -text -noout > /dev/null 2>&1
 check_cert=$?
 
 if [[ $check_cert -eq 0 ]]; then
-	run-parts --verbose "$DIR_LE/post-refresh.d/"
+    run-parts --verbose "$DIR_LE/post-refresh.d/"
 else 
-	if [[ $apache2_ssl_certificate == "$DIR_LE/signed.crt" ]]; then
-		ucr unset \
-			apache2/ssl/certificatechain \
-			apache2/ssl/certificate \
-			apache2/ssl/key
-		invoke-rc.d apache2 restart
-	fi
+    if [[ $apache2_ssl_certificate == "$DIR_LE/signed.crt" ]]; then
+        ucr unset \
+            apache2/ssl/certificatechain \
+            apache2/ssl/certificate \
+            apache2/ssl/key
+        invoke-rc.d apache2 restart
+    fi
 
-	if [[ $mail_dovecot_ssl_certificate == "$DIR_LE/chained.pem" ]]; then
-		ucr unset \
-			mail/dovecot/ssl/key \
-			mail/dovecot/ssl/certificate \
-			mail/dovecot/ssl/cafile
-		invoke-rc.d dovecot restart
-	fi
+    if [[ $mail_dovecot_ssl_certificate == "$DIR_LE/chained.pem" ]]; then
+        ucr unset \
+            mail/dovecot/ssl/key \
+            mail/dovecot/ssl/certificate \
+            mail/dovecot/ssl/cafile
+        invoke-rc.d dovecot restart
+    fi
 	
-	if [[ $mail_postfix_ssl_certificate == "$DIR_LE/signed.crt" ]]; then
-		ucr unset \
-			mail/postfix/ssl/key\
-			mail/postfix/ssl/certificate \
-			mail/postfix/ssl/cafile
-		invoke-rc.d postfix restart
-	fi
+    if [[ $mail_postfix_ssl_certificate == "$DIR_LE/signed.crt" ]]; then
+        ucr unset \
+            mail/postfix/ssl/key\
+            mail/postfix/ssl/certificate \
+            mail/postfix/ssl/cafile
+        invoke-rc.d postfix restart
+    fi
 fi
 
 status=$(tail -n1 /var/log/univention/letsencrypt.log)
